name: barcode_scanner_example
description: "Example app demonstrating weebi_barcode_scanner_package"

publish_to: 'none'

version: 1.6.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

  # Scanner package - contains all camera dependencies
  weebi_barcode_scanner:
    path: ../
  # OpenFoodFacts integration via separate package
  weebi_openfoodfacts_service: ^1.1.0    
  # Camera and image processing 
  camera: 0.10.5+5
  camera_windows: 0.2.6+2
  image: ^4.0.17
  path_provider: ^2.0.15
  path: ^1.8.3
  
  # Added for scanner implementation
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Example of proper asset setup for weebi_barcode_scanner package
  # These assets must be provided by the consuming application
  assets:
    # REQUIRED: YOLO barcode detection model (11.68 MB)
    # Download from: https://huggingface.co/weebi/weebi_barcode_detector/blob/main/best.rten
    # License: AGPL-3.0 (requires attribution)
    - assets/best.rten
    
    # PLATFORM-SPECIFIC: Include only what you need
    # Windows (10.87 MB)
    # - windows/rust_barcode_lib.dll  # Not needed - dart_barcode handles native loading
    
    # macOS (22 MB universal binary)  
    - macos/Frameworks/
    
    # Android (per architecture)
    # - android/jniLibs/arm64-v8a/librust_barcode_lib.so
    # - android/jniLibs/armeabi-v7a/librust_barcode_lib.so
    # - android/jniLibs/x86_64/librust_barcode_lib.so
    
    # iOS
    # - ios/Frameworks/librust_barcode_lib.dylib 