name: barcode_scanner_example
description: "Example app demonstrating weebi_barcode_scanner_package"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

  # Scanner package - contains all camera dependencies
  weebi_barcode_scanner:
    path: ../
    
  # Camera and image processing - EXACT working versions from dart_barcode_old
  camera: 0.10.5+5
  camera_windows: 0.2.6+2
  image: ^4.0.17
  path_provider: ^2.0.15
  path: ^1.8.3
  
  # Added for scanner implementation
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 