name: weebi_barcode_scanner
description: A simplified Flutter package for barcode and QR code scanning on Windows, powered by YOLO object detection and ZXing decoding.
version: 0.2.0+1  # Major version bump - FFI integration now working!
homepage: https://github.com/weebi-com/weebi_barcode_scanner
repository: https://github.com/weebi-com/weebi_barcode_scanner_package
issue_tracker: https://github.com/weebi-com/weebi_barcode_scanner_package/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Windows camera support
  camera: ^0.11.0+2
  camera_windows: ^0.2.6+2
  camera_macos: ^0.0.9
  
  # File handling
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Image processing
  image: ^4.0.17
  
  # FFI for native library integration
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - windows/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
