name: weebi_barcode_scanner
description: "Self-contained barcode scanner with real-time detection overlay. Features embedded YOLO detection, cross-platform support (Windows/macOS), point-of-sale optimizations, and OpenFoodFacts integration. No manual setup required."
version: 1.6.1
homepage: https://github.com/weebi-com/weebi_barcode_scanner
repository: https://github.com/weebi-com/weebi_barcode_scanner_package
issue_tracker: https://github.com/weebi-com/weebi_barcode_scanner_package/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Camera support for different platforms
  camera: ^0.10.5+5
  camera_windows: ^0.2.6+2
  camera_macos: ^0.0.9
  
  # File handling
  path: ^1.8.0
  
  # Core barcode detection engine
  weebi_barcode_dart: ^1.0.2
  # OpenFoodFacts integration via separate package
  weebi_openfoodfacts_service: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Plugin configuration for platform-specific implementations
  plugin:
    platforms:
      windows:
        dartPluginClass: WeebiBarcodeScanner
        pluginClass: WeebiBarcodePlugin
      macos:
        dartPluginClass: WeebiBarcodeScanner
        pluginClass: WeebiBarcodePlugin

  # Package assets - NO NATIVE LIBRARIES
  # Native libraries and models must be provided by consuming applications
  # See documentation for setup instructions
  # assets: 
  #   - README: Consuming apps must provide their own native assets
  #   - Required: assets/best.rten (11.68 MB)
  #   - Required Windows: windows/rust_barcode_lib.dll (10.87 MB)  
  #   - Required macOS: macos/Frameworks/librust_barcode_lib.dylib (22 MB total)

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - windows/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
